### ISSUE TITLE
Harvester for old website data

### ISSUE THREAD

**Issue by sirex** [ivpk/opendata.gov.lt#5]
There is a similar tool:

https://github.com/sirex/ckan-ivpk-import

But in this case we will be synchronizing data directly from MySQL database.

Code for this script is hosted here (based on the mentioned similar tool):

https://github.com/ivpk/opendata.gov.lt-mysql-import

### Todo

- [x] Data packages (datasets).
- [x] Add cron job to do the update continuously.
- [x] Package tags.
- [x] Contact information.
- [x] Organizations.
- [x] Synchronize groups.
- [ ] Investigate, maybe it is possible to import CSV resources into CKAN.

### Extra tasks:

- [x] Possibility to update groups if for example name has changed.
- [x] Delete groups if groups where deleted in IVPK database.

**Comment by sirex** [comment]
It was decided to refactor whole synchronization thing to a harvester and only synchronizing datasets.

**Comment by sirex** [comment]
@JustNindze I'm attaching list of links used in opendata.gov.lt packages, use these links to extract all package resources for each link.

[rinkmenos.csv.gz](https://github.com/ivpk/opendata.gov.lt/files/1501575/rinkmenos.csv.gz)
